"""One store, two backends, and one copy of the queries.

The discovery store is SQLite on a laptop and Postgres in a cluster, decided
2026-09-13 (#148). The fan-out writes from several pods, and SQLite's locking
depends on the filesystem honouring it, which is exactly what a ReadWriteMany
claim does not promise.

WHAT THIS IS NOT: a second copy of the SQL. `harness/memory_store.py` holds 33
statements and they stay there, in one dialect. This module translates that
dialect and derives the Postgres schema from the SQLite one, so the two
backends cannot drift apart in the way two hand-written schemas always do.

The translation is small because the incompatibilities were counted rather than
feared: 33 `?`-style statements, 2 `.lastrowid`, 4 SQLite-only upserts, 5
`INTEGER PRIMARY KEY`, 1 row factory.

ONE CONNECTION PER PROCESS, NOT A POOL, and that is a statement about the
workloads rather than an oversight. Every caller here is a short single-threaded
run: the CLI, or a Job that does one thing and exits. A shared connection under
real concurrency is a known corruption (a commit folds into another thread's
open transaction); if a long-lived multi-threaded service ever reads this store,
it needs a psycopg pool before it needs anything else.
"""
from __future__ import annotations

import os
import re

SQLITE, POSTGRES = "sqlite", "postgres"
BACKEND_ENV = "LOCALHARNESS_STORE"

#: Postgres REAL is float4. A unix timestamp needs ten significant digits and
#: float4 carries about seven, so `first_seen` would silently round to the
#: nearest couple of minutes and every recurrence window would be wrong by an
#: amount nobody would think to look for. DOUBLE PRECISION is float8.
_TYPES = ((r"\bREAL\b", "DOUBLE PRECISION"),
          (r"\bINTEGER PRIMARY KEY\b",
           "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"))

#: SQLite's `OR IGNORE` means "skip a row that violates any unique constraint",
#: which is `ON CONFLICT DO NOTHING` with no target. `OR REPLACE` is an upsert
#: and has to name the key, so it is handled per-statement rather than by a
#: blanket rule.
_OR_IGNORE = re.compile(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", re.I)
_OR_REPLACE = re.compile(r"\bINSERT\s+OR\s+REPLACE\s+INTO\s+(\w+)\b", re.I)

#: An upsert has to say what it conflicts on, and SQLite's OR REPLACE does not.
#: Recorded per table rather than inferred, so adding a table that needs one
#: fails loudly here instead of silently inserting duplicates.
_UPSERT_KEYS = {"meta": "key"}
_UPSERT_SET = {"meta": ("value",)}


def backend() -> str:
    """Which store this process talks to. SQLite unless told otherwise, because
    `lh` on a laptop must keep working with no cluster at all."""
    got = (os.environ.get(BACKEND_ENV) or SQLITE).strip().lower()
    return POSTGRES if got == POSTGRES else SQLITE


def placeholders(sql: str) -> str:
    """`?` to `%s`, except where a `?` is not a placeholder.

    THREE CONTEXTS, and the third was found the hard way. A blanket replace
    rewrites question marks inside string literals, which yields a query that
    runs and returns the wrong rows rather than one that raises. It also
    rewrites them inside COMMENTS -- and the comment that exposed this was one
    explaining a different portability bug, which quoted `HAVING times >= ?`
    and so grew a second placeholder for a query with one parameter.

    psycopg counts placeholders before binding, so that one at least fails
    loudly: "the query has 2 placeholders but 1 parameters were passed".
    """
    out = []
    i, n = 0, len(sql)
    quote = None
    while i < n:
        ch = sql[i]
        if quote:
            out.append(ch)
            if ch == quote:
                quote = None
            i += 1
        elif ch in "'\"":
            quote = ch
            out.append(ch)
            i += 1
        elif sql.startswith("--", i):
            end = sql.find("\n", i)
            end = n if end == -1 else end
            out.append(sql[i:end])
            i = end
        elif sql.startswith("/*", i):
            end = sql.find("*/", i + 2)
            end = n if end == -1 else end + 2
            out.append(sql[i:end])
            i = end
        elif ch == "?":
            out.append("%s")
            i += 1
        else:
            out.append(ch)
            i += 1
    return "".join(out)


def translate(sql: str) -> str:
    """One SQLite statement, as Postgres would have it.

    Only three things differ, and each is a construct rather than a dialect:
    the placeholder style, `OR IGNORE`, and `OR REPLACE`.
    """
    if _OR_IGNORE.search(sql):
        sql = _OR_IGNORE.sub("INSERT INTO", sql)
        # No conflict TARGET on purpose: SQLite's OR IGNORE skips a row that
        # violates ANY unique constraint, and naming one column here would
        # quietly stop ignoring the others.
        sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    m = _OR_REPLACE.search(sql)
    if m:
        table = m.group(1)
        key = _UPSERT_KEYS.get(table)
        if key is None:
            raise ValueError(
                f"INSERT OR REPLACE INTO {table} has no recorded conflict key. "
                f"An upsert must name what it conflicts on; add {table} to "
                f"_UPSERT_KEYS rather than guessing here.")
        cols = _UPSERT_SET[table]
        sql = _OR_REPLACE.sub(f"INSERT INTO {table}", sql)
        assignments = ", ".join(f"{c} = EXCLUDED.{c}" for c in cols)
        sql = (sql.rstrip().rstrip(";")
               + f" ON CONFLICT ({key}) DO UPDATE SET {assignments}")
    return placeholders(sql)


def postgres_ddl(sqlite_ddl: str) -> str:
    """DERIVED, never hand-written. Two schemas maintained by hand diverge, and
    the divergence shows up as a column that exists on one backend only."""
    out = sqlite_ddl
    for pattern, replacement in _TYPES:
        out = re.sub(pattern, replacement, out)
    return out


#: `.lastrowid` is a SQLite idea. Postgres returns it, so an INSERT that a
#: caller reads an id from has to ASK, and only a plain INSERT can: one that
#: may do nothing on conflict returns no row.
_PLAIN_INSERT = re.compile(r"^\s*INSERT\s+INTO\b", re.I)


class Cursor:
    """The half of a sqlite3.Cursor that harness/memory_store.py uses."""

    def __init__(self, cur, lastrowid=None):
        self._cur = cur
        self.lastrowid = lastrowid

    def fetchone(self):
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()

    def __iter__(self):
        return iter(self._cur)


class PostgresConnection:
    """A sqlite3.Connection-shaped view of a psycopg connection.

    Shaped rather than complete: it implements what the 33 statements in
    memory_store actually use. A method nobody calls is a method nobody has
    tested, and this file is small on purpose.
    """

    def __init__(self, conn):
        self._conn = conn

    def execute(self, sql: str, params=()):
        translated = translate(sql)
        wants_id = (_PLAIN_INSERT.match(translated)
                    and "ON CONFLICT" not in translated.upper()
                    and "RETURNING" not in translated.upper())
        if wants_id:
            translated += " RETURNING id"
        cur = self._conn.cursor()
        cur.execute(translated, tuple(params))
        if wants_id:
            row = cur.fetchone()
            return Cursor(cur, lastrowid=row["id"] if row else None)
        return Cursor(cur)

    def executescript(self, ddl: str):
        self._conn.cursor().execute(postgres_ddl(ddl))
        self._conn.commit()

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()


def dsn(environ=None) -> str:
    """Where the cluster's Postgres is, from the environment the chart sets."""
    e = os.environ if environ is None else environ
    host = e.get("PGHOST", "localhost")
    port = e.get("PGPORT", "5432")
    db = e.get("PGDATABASE", "discovery")
    user = e.get("PGUSER", "discovery")
    password = e.get("PGPASSWORD", "")
    return f"host={host} port={port} dbname={db} user={user} password={password}"


def postgres_connect(environ=None):
    """Open the cluster store. Imported lazily so a laptop never needs psycopg."""
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as exc:  # pragma: no cover - exercised by the message
        raise RuntimeError(
            f"{BACKEND_ENV}=postgres needs psycopg: uv sync --group cluster"
        ) from exc
    return PostgresConnection(
        psycopg.connect(dsn(environ), row_factory=dict_row, autocommit=False))
